### ISSUE TITLE
缺少 @xml/provider_paths 

### ISSUE THREAD

**Issue by invader41** [vaenow/cordova-plugin-app-update#40] opened 2017-09-13 05:54 UTC
缺少 xml/provider_paths

**Comment by bonbers** [comment] 2017-09-13 14:10
I have a same error.

BUILD FAILED .

error: Error: No resource found that matches the given name (at 'resource' with value 
        '@xml/provider_paths').

**Comment by vaenow** [comment] 2017-09-13 14:58
目前还不确定这是什么问题，请贴出具体复现步骤

**Comment by invader41** [comment] 2017-09-14 01:19
res/xml/provider_paths.xml 文件缺失导致编译失败。
我自己加了一个：

<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-path name="download" path="download/"/>
</paths>

**Comment by cimran** [comment] 2017-09-15 23:08
I have a same error.

BUILD FAILED .

error: Error: No resource found that matches the given name (at 'resource' with value '@ xml/provider_paths').

I have tried adding file as mentioned by invader41 but still getting this error. Could you please ?

This is the error:
platforms\android\build\intermediates\manifests\full\debug\AndroidManifest.xml:111:35-54: AAPT: No resource found that matches the given name (at 'resource' with value '@xml/provider_paths').

**Comment by cimran** [comment] 2017-09-16 11:59
I have managed to fix this issue by putting xml file into Android res folder. The plugin displays that new update found and then hangs at Updating view with option UPDATE IN BACKGROUND but nothing happens. Any idea where I need to check please? I have the file and apk sitting there on the server.

**Comment by cimran** [comment] 2017-09-16 12:41
I found that issue. need to add web config entry for .apk file to allow as a static content. (MIME Type)

Working perfect now!
Thanks.

**Comment by otchereErnest** [comment] 2017-09-23 21:50
@cimran Please can you help me out with how you did it. i tried your method.. but the app crashes anytime it tries fetching the update. any help will be much appreciated. Thanks

**Comment by thisisjeevanraj** [comment] 2017-09-25 09:37
Hi i'm also having the same error while building the apk. Any solution to fix the issue is much appreciated
Here is my log file
Build Date: 2017-09-25 09:32:16 +0000
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "cordova-plugin-actionsheet@2.3.1" via npm
Installing "cordova-plugin-actionsheet" at "2.3.1" for android
Fetching plugin "cordova-plugin-contacts@2.0.1" via npm
Installing "cordova-plugin-contacts" at "2.0.1" for android
Fetching plugin "cordova-plugin-device@1.1.1" via npm
Installing "cordova-plugin-device" at "1.1.1" for android
Fetching plugin "https://github.com/apache/cordova-plugin-geolocation" via git clone
Using shallow clone
Repository "https://github.com/apache/cordova-plugin-geolocation" checked out to git ref "master" at "5e472fd".
Installing "cordova-plugin-geolocation" at "2.4.4-dev" for android
Fetching plugin "cordova-plugin-compat@^1.0.0" via npm
Installing "cordova-plugin-compat" at "1.2.0" for android
Fetching plugin "cordova-plugin-network-information@1.2.0" via npm
Installing "cordova-plugin-network-information" at "1.2.0" for android
Fetching plugin "cordova-plugin-splashscreen@2.1.0" via npm
Installing "cordova-plugin-splashscreen" at "2.1.0" for android
Fetching plugin "cordova-plugin-statusbar@2.1.0" via npm
Installing "cordova-plugin-statusbar" at "2.1.0" for android
Fetching plugin "cordova-plugin-themeablebrowser@0.2.17" via npm
Installing "cordova-plugin-themeablebrowser" at "0.2.17" for android
Fetching plugin "https://github.com/OneSignal/OneSignal-Cordova-Dependencies-Compat" via git clone
Using shallow clone
Repository "https://github.com/OneSignal/OneSignal-Cordova-Dependencies-Compat" checked out to git ref "master" at "4565b15".
Installing "onesignal-cordova-dependencies-compat" at "1.0.0" for android
Fetching plugin "https://github.com/one-signal/OneSignal-Cordova-SDK.git" via git clone
Using shallow clone
Repository "https://github.com/one-signal/OneSignal-Cordova-SDK.git" checked out to git ref "PGB-Compat" at "cb5546c".
Installing "onesignal-cordova-plugin-pgb-compat" at "2.0.10" for android
Fetching plugin "uk.co.workingedge.phonegap.plugin.launchnavigator@3.2.1" via npm
Installing "uk.co.workingedge.phonegap.plugin.launchnavigator" at "3.2.1" for android
Plugin dependency "cordova-plugin-actionsheet@2.3.1" already fetched, using that version.
Dependent plugin "cordova-plugin-actionsheet" already installed on android.
Fetching plugin "https://github.com/dpa99c/cordova-plugin-request-location-accuracy" via git clone
Using shallow clone
Repository "https://github.com/dpa99c/cordova-plugin-request-location-accuracy" checked out to git ref "master" at "915b178".
Installing "cordova-plugin-request-location-accuracy" at "2.2.2" for android
Fetching plugin "https://github.com/413326885/cordova-plugin-x-toast" via git clone
Using shallow clone
Repository "https://github.com/413326885/cordova-plugin-x-toast" checked out to git ref "master" at "f3767b4".
Installing "cordova-plugin-x-toast" at "2.2.1" for android
Fetching plugin "cordova-plugin-ionic-keyboard@1.0.5" via npm
Installing "cordova-plugin-ionic-keyboard" at "1.0.5" for android
Fetching plugin "https://github.com/tjwoon/csZBar" via git clone
Using shallow clone
Repository "https://github.com/tjwoon/csZBar" checked out to git ref "master" at "fc5dcc3".
Installing "cordova-plugin-cszbar" at "1.3.2" for android
Fetching plugin "https://github.com/vaenow/cordova-plugin-app-update" via git clone
Using shallow clone
Repository "https://github.com/vaenow/cordova-plugin-app-update" checked out to git ref "master" at "47e6f62".
Installing "cordova-plugin-app-update" at "1.3.10" for android
Fetching plugin "cordova-plugin-appversion@1.0.0" via npm
Installing "cordova-plugin-appversion" at "1.0.0" for android
Plugin "cordova-plugin-appversion" already installed on android. Making it top-level.
Fetching plugin "cordova-plugin-whitelist@1.2.2" via npm
Installing "cordova-plugin-whitelist" at "1.2.2" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
Configuration on demand is an incubating feature.
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:preReleaseBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:compileDebugAidl
:CordovaLib:generateDebugBuildConfig
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:compileReleaseAidl
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets
:CordovaLib:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:compileReleaseJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareComAndroidSupportSupportCompat2520Library
:prepareComAndroidSupportSupportCoreUi2520Library
:prepareComAndroidSupportSupportCoreUtils2520Library
:prepareComAndroidSupportSupportFragment2520Library
:prepareComAndroidSupportSupportMediaCompat2520Library
:prepareComAndroidSupportSupportV42520Library
:prepareComGoogleAndroidGmsPlayServicesAnalytics1104Library
:prepareComGoogleAndroidGmsPlayServicesAnalyticsImpl1104Library
:prepareComGoogleAndroidGmsPlayServicesBase1104Library
:prepareComGoogleAndroidGmsPlayServicesBasement1104Library
:prepareComGoogleAndroidGmsPlayServicesGcm1104Library
:prepareComGoogleAndroidGmsPlayServicesIid1104Library
:prepareComGoogleAndroidGmsPlayServicesLocation1104Library
:prepareComGoogleAndroidGmsPlayServicesTagmanagerV4Impl1104Library
:prepareComGoogleAndroidGmsPlayServicesTasks1104Library
:prepareProjectCordovaLibUnspecifiedDebugLibrary
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResources/project/build/intermediates/manifests/full/debug/AndroidManifest.xml:163:35-54 : AAPT: No resource found that matches the given name (at 'resource' with value '@xml/provider_paths').

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/android-sdk/build-tools/24.0.1/aapt'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.28 secs
undefined

**Comment by y276827893** [comment] 2017-09-25 18:26
如@invader41所说，在xml目录下增加一个xml文件可解决。

**Closed** 2017-10-08 08:26 UTC
